In [66]:
import pandas as pd
import numpy as np
true = np.arange(1,11,1)
np.random.seed(1031)
pred = np.arange(1,11,1) + np.random.randint(-1,2,10)
data = pd.DataFrame({'true':true,
              'pred':pred})
data

   true  pred
0     1     1
1     2     1
2     3     2
3     4     5
4     5     6
5     6     6
6     7     6
7     8     7
8     9     9
9    10    10

In [14]:
#this is to create a new data stream called e for error and then defining how to get it
(
    data.assign(e = data.true - data.pred)
)

   true  pred  e
0     1     1  0
1     2     1  1
2     3     2  1
3     4     5 -1
4     5     6 -1
5     6     6  0
6     7     6  1
7     8     7  1
8     9     9  0
9    10    10  0

In [13]:
#ae is absolute error ie there is no -ves only +ves
(
    data.assign(e = data.true - data.pred,
                ae = np.abs(data.true - data.pred))
)

   true  pred  e  ae
0     1     1  0   0
1     2     1  1   1
2     3     2  1   1
3     4     5 -1   1
4     5     6 -1   1
5     6     6  0   0
6     7     6  1   1
7     8     7  1   1
8     9     9  0   0
9    10    10  0   0

In [12]:
#se for squared error non absolute coz squaring nullifies -ve
(
    data.assign(e = data.true - data.pred,
                ae = np.abs(data.true - data.pred),
               se = (data.true - data.pred)**2)
)

   true  pred  e  ae  se
0     1     1  0   0   0
1     2     1  1   1   1
2     3     2  1   1   1
3     4     5 -1   1   1
4     5     6 -1   1   1
5     6     6  0   0   0
6     7     6  1   1   1
7     8     7  1   1   1
8     9     9  0   0   0
9    10    10  0   0   0

In [16]:
#root mean squared error RMSE
(
    data.assign(e = data.true - data.pred,
                ae = np.abs(data.true - data.pred),
               se = (data.true - data.pred)**2)
    .se.mean()
)

np.float64(0.6)

In [17]:
from sklearn.metrics import root_mean_squared_error, r2_score, mean_absolute_error

In [20]:
## or you can just use import sklearn but it will use too much RAM
## you can also use "import root_mean_squared_error as rmse, ..."

In [24]:
root_mean_squared_error(true, pred)
#lower is better

0.7745966692414834

In [27]:
mean_absolute_error(true, pred)
#which we did manually in code line 16 so recheck there

0.6

In [26]:
r2_score(true, pred)
#higher is better
#range from 0 to 1
#ignores the use of the data

0.9272727272727272

In [29]:
np.random.seed(1031)
true = np.random.choice(a = [0,1],size = 10, replace = True)
pred_prob = np.random.random_sample(size = 10)
data = pd.DataFrame({'true':true,
                     'pred_prob':pred_prob})
data
#pred prob is the probability of it being 1

   true  pred_prob
0     1   0.957739
1     0   0.196257
2     1   0.560088
3     0   0.828882
4     1   0.745089
5     0   0.507090
6     0   0.758294
7     1   0.083193
8     1   0.647319
9     0   0.387810

In [39]:
np.random.seed(1031)
true = np.random.choice(a = [0,1],size = 10, replace = True)
pred_prob = np.random.random_sample(size = 10)
data = pd.DataFrame({'true':true,
                     'pred_prob':pred_prob})
(data.pred_prob>0.5)

0     True
1    False
2     True
3     True
4     True
5     True
6     True
7    False
8     True
9    False
Name: pred_prob, dtype: bool

In [37]:
np.random.seed(1031)
true = np.random.choice(a = [0,1],size = 10, replace = True)
pred_prob = np.random.random_sample(size = 10)
data = pd.DataFrame({'true':true,
                     'pred_prob':pred_prob})
data['pred'] = (data.pred_prob>0.5)
data

   true  pred_prob   pred
0     1   0.957739   True
1     0   0.196257  False
2     1   0.560088   True
3     0   0.828882   True
4     1   0.745089   True
5     0   0.507090   True
6     0   0.758294   True
7     1   0.083193  False
8     1   0.647319   True
9     0   0.387810  False

In [36]:
np.random.seed(1031)
true = np.random.choice(a = [0,1],size = 10, replace = True)
pred_prob = np.random.random_sample(size = 10)
data = pd.DataFrame({'true':true,
                     'pred_prob':pred_prob})
data['pred'] = (data.pred_prob>0.5).astype('int')
data

   true  pred_prob  pred
0     1   0.957739     1
1     0   0.196257     0
2     1   0.560088     1
3     0   0.828882     1
4     1   0.745089     1
5     0   0.507090     1
6     0   0.758294     1
7     1   0.083193     0
8     1   0.647319     1
9     0   0.387810     0

In [42]:
np.random.seed(1031)
true = np.random.choice(a = [0,1],size = 10, replace = True)
pred_prob = np.random.random_sample(size = 10)
data = pd.DataFrame({'true':true,
                     'pred_prob':pred_prob})
data['pred'] = (data.pred_prob>0.5).astype('int')
from sklearn.metrics import accuracy_score
accuracy_score (data.true, data.pred)
#accuracy as in they were correct in 60% of the cases hence 0.6

0.6

In [44]:
##R2 = 1 is perfect prediction
#Bias variance Tradeoff wherein after a point test min and then starts increasing but on the contrary training keeps getting better as complexity increases but the prediction error keeps increasing after a point

In [45]:
## We will take the data and then split it into training and test data sets fit the code into train data only!!

In [121]:
import numpy as np
import pandas as pd
data = pd.read_csv('/Users/chintanjikkar/Desktop/PACE/Fall 25/Predictive Analytics/codes/Data/territory_sales.csv')

In [122]:
#never peek at the data while you are gonna use it for train and test as it might create biasness

In [123]:
###DID it later
#train = data.sample(frac = 0.7,random_state=1031)
#test = data.drop(labels = train.index)

In [124]:
data.sample(frac = 0.8)
#this will give you 80% of the sample chosen at random

    territory_num region  number_of_salespersons   sales
11             12   East                       7   54040
29             30  South                      10   56822
73             74  South                      13   65127
22             23  South                      18   80579
40             41  South                      17  136298
..            ...    ...                     ...     ...
54             55   West                       5   33650
72             73  North                       8   41931
1               2  South                      17  153956
78             79  South                      18  182478
93             94  South                       8   32166

[80 rows x 4 columns]

In [125]:
train = data.sample(frac = 0.8, random_state=617)
test = data.drop(train.index, axis= 0) 
#test = from data drop all the train rows ie test = Data - train sample
len(train), len(test)

(80, 20)

In [126]:
train.head()

    territory_num region  number_of_salespersons   sales
26             27  North                       8   32221
85             86   West                      24  217461
93             94  South                       8   32166
79             80   East                       8   46220
59             60   East                      25  145135

In [127]:
train.loc[:,'sales']
train.sales
#this is to locate just the sales column

26     32221
85    217461
93     32166
79     46220
59    145135
       ...
29     56822
39    185656
37     54586
91     64057
51     60727
Name: sales, Length: 80, dtype: int64

In [128]:
train.loc[:,'number_of_salespersons']
train.number_of_salespersons

26     8
85    24
93     8
79     8
59    25
      ..
29    10
39    24
37    10
91     8
51     9
Name: number_of_salespersons, Length: 80, dtype: int64

In [129]:
#majority dont use pandas to split data for their models they use scikit learn to split it and is called train test split

In [130]:
from sklearn.model_selection import train_test_split

In [131]:
Y = data.sales
X = data.loc[:,['region','number_of_salespersons']]

In [132]:
train_test_split(X,Y)

[   region  number_of_salespersons
 26  North                       8
 49   East                      16
 2   North                      13
 38   East                       7
 58  South                      23
 ..    ...                     ...
 27   West                      24
 54   West                       5
 75  South                      11
 72  North                       8
 56  South                      19

 [75 rows x 2 columns],
    region  number_of_salespersons
 44  South                      25
 81  North                      14
 77   West                      22
 47   East                       8
 35   West                      21
 21   East                       7
 9    West                      18
 6   North                      20
 40  South                      17
 14  South                      21
 7    East                      11
 32   East                      23
 23  North                      11
 10   East                      15
 69   East                      19
 57  North                       8
 88  South                      11
 83   East                      24
 46  South                      17
 15   East                      14
 60   West                      19
 93  South                       8
 17   West                      16
 4   North                       5
 16   East                      21,
 26     32221
 49    137504
 2     101151
 38     37490
 58    132797
        ...
 27    111155
 54     33650
 75     49786
 72     41931
 56    124970
 Name: sales, Length: 75, dtype: int64,
 44    170137
 81     69772
 77    163292
 47     53180
 35    147885
 21     42133
 9     144999
 6     131286
 40    136298
 14    134147
 7      35988
 32    186373
 23     50435
 10     98744
 69    160757
 57     73726
 88     78248
 83    149008
 46    100832
 15     84762
 60    104405
 93     32166
 17     74789
 4      41042
 16    112857
 Name: sales, dtype: int64]

In [133]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.8)

In [134]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape
#this is to figure out the shape

((20, 2), (80, 2), (20,), (80,))

In [ ]:
Y_train.shape
Y_test.shape

In [135]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,
                                                    test_size=0.8,
                                                   random_state=617)

In [136]:
Y_train.mean()

np.float64(96928.8)

In [137]:
Y_test.mean()
##Both of them should have mostly identical mean since they are randomly selected and are very similar to each other, so we use stratified random sampling

np.float64(99289.1875)

In [140]:
#stratifies random sampling
pd.qcut(data.sales, q = 10).value_counts()

sales
(24698.999, 40262.9]    10
(40262.9, 49627.2]      10
(49627.2, 62647.1]      10
(62647.1, 79646.6]      10
(79646.6, 96667.5]      10
(96667.5, 111621.0]     10
(111621.0, 131989.8]    10
(131989.8, 145026.2]    10
(145026.2, 162951.8]    10
(162951.8, 217461.0]    10
Name: count, dtype: int64

In [141]:
data.sort_values('sales').head(10)
#this is how they create strata by taking 10 *10 time sthats 100 data points and them averaging them

    territory_num region  number_of_salespersons  sales
96             97  North                       7  24699
48             49  South                       5  28134
99            100  South                       6  29114
13             14  North                       5  30463
93             94  South                       8  32166
26             27  North                       8  32221
54             55   West                       5  33650
7               8   East                      11  35988
38             39   East                       7  37490
82             83  South                      12  38075

In [144]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,
                                                    test_size=0.8,
                                                   random_state=617,
                                                   stratify=pd.qcut(data.sales,q=10))
#this helps us incorporate the stratifying part into the original code line seamlessly

In [147]:
Y_train.mean(), Y_test.mean()

(np.float64(101648.75), np.float64(98109.2))

In [148]:
###NO FREE LUNCH THEOREM
#the process of modelling is not liner there is a lot of back and forth with lots of iterations

In [149]:
#when you describe your data descriptive stats
#when you draw infrernce form that said data its inferential stats (prob of something happening, changes x happens)
##p value is less than alpha <0.5 it is significant 
#pvalue = prob of this number being 0 and outside your sample ie if its 0.002 it is 0.2% of it being 0 and outside the sample and its very small